# Generated by Django 5.2.3 on 2025-06-13 02:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Author",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(blank=True, max_length=100, unique=True)),
                ("name", models.CharField(max_length=100)),
            ],
            options={
                "verbose_name": "Author",
            },
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                ("slug", models.SlugField(max_length=100, unique=True)),
                ("username", models.CharField(max_length=50)),
                (
                    "email",
                    models.EmailField(
                        max_length=254, primary_key=True, serialize=False
                    ),
                ),
                ("phone", models.CharField(max_length=20)),
                ("address", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(blank=True, max_length=100, unique=True)),
                ("title", models.CharField(max_length=200)),
                ("date_of_pub", models.DateField()),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "genre",
                    models.CharField(
                        choices=[
                            ("horror", "Horror"),
                            ("self_help", "Self Help"),
                            ("adventure", "Adventure"),
                            ("others", "Others"),
                        ],
                        default="others",
                        max_length=20,
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="books",
                        to="books.author",
                    ),
                ),
            ],
            options={
                "verbose_name": "Book",
                "ordering": ["date_of_pub"],
            },
        ),
        migrations.CreateModel(
            name="Collection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(blank=True, max_length=100, unique=True)),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "books",
                    models.ManyToManyField(related_name="collections", to="books.book"),
                ),
            ],
            options={
                "verbose_name": "Book_Collection",
                "db_table": "book_collection",
            },
        ),
        migrations.AddField(
            model_name="author",
            name="profile",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="author",
                to="books.profile",
            ),
        ),
        migrations.CreateModel(
            name="Publisher",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(blank=True, max_length=100, unique=True)),
                ("name", models.CharField(max_length=100, unique=True)),
                ("website", models.URLField()),
                ("email", models.EmailField(max_length=254)),
                ("address", models.TextField()),
            ],
            options={
                "verbose_name": "Publisher",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("name",), name="unique_publisher_name"
                    )
                ],
            },
        ),
        migrations.AddField(
            model_name="book",
            name="publisher",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="books",
                to="books.publisher",
            ),
        ),
        migrations.AddConstraint(
            model_name="book",
            constraint=models.UniqueConstraint(
                fields=("author", "title", "date_of_pub"),
                name="unique_author_title_date",
            ),
        ),
    ]
