"""This module calculates the sum of even and odd Fibonacci numbers."""

# # Problem 2

# Each new term in the Fibonacci sequence is generated by
# adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

# ```
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# ```

# ## Part A

# Find the sum of the even-valued terms in
# the Fibonacci sequence whose values do not exceed four million.

# Edit the file answer.py and update the function `answer()` to return the answer.

# ```
# answer()
# ```

# ## Part B

# Write a function in python that returns the sum of all even and/or odd
# terms of the Fibonacci sequence that are inside the range defined by
# `start` and `end` inclusive.

# Consider even numbers when `even` is True and disregard when `even` is False.

# Consider odd numbers when `odd` is True and disregard when `odd` is False.

# Edit the file solver.py to update the function `solver` to return the
# answer when called as in the below example.

# The function should return `None` if `start` is greater than `end`.


def answer():
    """
    Returns the sum of even-valued terms in the Fibonacci sequence
    """
    total = 0
    num1 = 0
    num2 = 1

    number = num1 + num2

    while number <= 4000000:
        if number % 2 == 0:
            total += number

        num1 = num2
        num2 = number
        number = num1 + num2
    return total


print(answer())

# o/p: 4613732


# ***correct code***#
def solver(start, end, even=False, odd=False):
    """
    Returns the sum of Fibonacci numbers between start and end (inclusive).
    Includes even numbers if `even` is True, odd numbers if `odd` is True.
    Returns None if start > end.
    """
    if start > end:
        return None
    if not even and not odd:
        return 0

    num1, num2 = 0, 1
    total = 0

    while num1 <= end:
        if num1 >= start:
            if (even and num1 % 2 == 0) or (odd and num1 % 2 != 0):
                total += num1
        num1, num2 = num2, num1 + num2

    return total


# Example usage
print(solver(1, 10, even=True, odd=False))  # Output: 10
